// Code generated by hertz generator.

package agent

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _handlechatMw() []app.HandlerFunc {
	// your code...
	return nil
}
