// Code generated by hertz generator.

package oss

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadimageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}
