// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _alipayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _payresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paysuccessMw() []app.HandlerFunc {
	// your code...
	return nil
}
