// Code generated by hertz generator.

package merchant

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/tiktokmall/backend/app/frontend/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantpingMw() []app.HandlerFunc {
	// your code...
	return nil
}

// 保护 merchant/product 下的所有路由
func _productMw() []app.HandlerFunc {
	// your code...
	// 保护 merchant/product 下的所有路由
	return []app.HandlerFunc{middleware.MerchantProduct()}
}

func _merchantaddproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantdeleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetproductdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetproductlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantupdateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}
