// Code generated by hertz generator.

package merchant

import (
	"log"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _marchantMw() []app.HandlerFunc {
	// your code...
	log.Println("merchant: hello world")
	return nil
}

func _merchantauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantaddproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantdeleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetproductdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantgetproductlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _merchantupdateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}
