// Code generated by hertz generator.

package cart

import (
	"github.com/tiktokmall/backend/app/frontend/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.Jwt()}
}

func _addcartitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _emptycartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeqtyMw() []app.HandlerFunc {
	// your code...
	return nil
}
