// Code generated by hertz generator.

package main

import (
	"context"
	"os"
	"time"

	"github.com/tiktokmall/backend/app/frontend/biz/router"
	"github.com/tiktokmall/backend/app/frontend/conf"
	"github.com/tiktokmall/backend/app/frontend/infra/rpc"
	"github.com/tiktokmall/backend/app/frontend/middleware"
	"github.com/tiktokmall/backend/common/mtl"

	frontendUtils "github.com/tiktokmall/backend/app/frontend/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	prometheus "github.com/hertz-contrib/monitor-prometheus"
	hertzoblogrus "github.com/hertz-contrib/obs-opentelemetry/logging/logrus"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/hertz-contrib/sessions"
	"github.com/hertz-contrib/sessions/redis"
	"github.com/joho/godotenv"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

var (
	ServiceName  = frontendUtils.ServiceName
	MetricsPort  = conf.GetConf().Hertz.MetricsPort
	RegisterAddr = conf.GetConf().Hertz.RegistryAddr
)

func main() {
	// load .env file to environment variables
	_ = godotenv.Load()

	consul, registryInfo := mtl.InitMetric(ServiceName, MetricsPort, RegisterAddr)
	defer consul.Deregister(registryInfo)
	// init dal
	// dal.Init()

	// user 服务发现
	rpc.Init()
	address := conf.GetConf().Hertz.Address

	// p := provider.NewOpenTelemetryProvider(
	// 	provider.WithServiceName(ServiceName),
	// 	provider.WithExportEndpoint("localhost:4317"),
	// 	provider.WithInsecure(),
	// )
	// defer p.Shutdown(context.Background())
	tracer, cfg := hertztracing.NewServerTracer()

	// 将 prometheus 注册到 hertz 的中间件中
	h := server.New(
		server.WithHostPorts(address),
		server.WithTracer(prometheus.NewServerTracer("", "",
			prometheus.WithDisableServer(true),
			prometheus.WithRegistry(mtl.Registry),
		)),
		// 添加 tracing
		tracer,
	)

	h.Use(hertztracing.ServerMiddleware(cfg))

	registerMiddleware(h)

	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		hlog.CtxInfof(c, "ping pong test log collect.")
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	// proto 文件中定义的路由服务
	router.GeneratedRegister(h)
	// 加载模板文件
	h.LoadHTMLGlob("template/*")
	// 加载静态文件
	h.Static("/static", "./") // 在当前目录下寻找 static 文件夹

	h.GET("/sign-in", func(c context.Context, ctx *app.RequestContext) {
		// tmpl {{ }} 使用 define 中的名称
		ctx.HTML(consts.StatusOK, "sign-in",
			utils.H{"title": "Sign In", "next": ctx.Query("next")})
	})

	h.GET("/sign-up", func(c context.Context, ctx *app.RequestContext) {
		// tmpl {{ }} 使用 define 中的名称
		ctx.HTML(consts.StatusOK, "sign-up", utils.H{"title": "Sign Up"})
	})
	h.Spin()
}

func registerMiddleware(h *server.Hertz) {
	//

	store, _ := redis.NewStore(10, "tcp", conf.GetConf().Redis.Address, "", []byte(os.Getenv("SESSION_SECRET")))
	h.Use(sessions.New("cloudwego-shop", store))
	// log
	logger := hertzoblogrus.NewLogger(hertzoblogrus.WithLogger(hertzlogrus.NewLogger().Logger()))
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	var flushInterval time.Duration
	if os.Getenv("GO_ENV") == "online" {
		flushInterval = time.Minute
	} else {
		flushInterval = time.Second
	}
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: flushInterval,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	// auth
	middleware.Register(h)
}
