// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echoservice

import (
	pbapi "bytetech/course/demo/demo_proto/kitex_gen/pbapi"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EchoMethod(ctx context.Context, Req *pbapi.EchoRequest, callOptions ...callopt.Option) (r *pbapi.EchoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kEchoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEchoServiceClient struct {
	*kClient
}

func (p *kEchoServiceClient) EchoMethod(ctx context.Context, Req *pbapi.EchoRequest, callOptions ...callopt.Option) (r *pbapi.EchoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EchoMethod(ctx, Req)
}
