// Code generated by Kitex v0.9.1. DO NOT EDIT.

package echoservice

import (
	pbapi "bytetech/course/demo/demo_proto/kitex_gen/pbapi"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"EchoMethod": kitex.NewMethodInfo(
		echoMethodHandler,
		newEchoMethodArgs,
		newEchoMethodResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	echoServiceServiceInfo                = NewServiceInfo()
	echoServiceServiceInfoForClient       = NewServiceInfoForClient()
	echoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return echoServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return echoServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return echoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EchoService"
	handlerType := (*pbapi.EchoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pbapi",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func echoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(pbapi.EchoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(pbapi.EchoService).EchoMethod(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *EchoMethodArgs:
		success, err := handler.(pbapi.EchoService).EchoMethod(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*EchoMethodResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newEchoMethodArgs() interface{} {
	return &EchoMethodArgs{}
}

func newEchoMethodResult() interface{} {
	return &EchoMethodResult{}
}

type EchoMethodArgs struct {
	Req *pbapi.EchoRequest
}

func (p *EchoMethodArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(pbapi.EchoRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *EchoMethodArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *EchoMethodArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *EchoMethodArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *EchoMethodArgs) Unmarshal(in []byte) error {
	msg := new(pbapi.EchoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var EchoMethodArgs_Req_DEFAULT *pbapi.EchoRequest

func (p *EchoMethodArgs) GetReq() *pbapi.EchoRequest {
	if !p.IsSetReq() {
		return EchoMethodArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *EchoMethodArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *EchoMethodArgs) GetFirstArgument() interface{} {
	return p.Req
}

type EchoMethodResult struct {
	Success *pbapi.EchoResponse
}

var EchoMethodResult_Success_DEFAULT *pbapi.EchoResponse

func (p *EchoMethodResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(pbapi.EchoResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *EchoMethodResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *EchoMethodResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *EchoMethodResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *EchoMethodResult) Unmarshal(in []byte) error {
	msg := new(pbapi.EchoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *EchoMethodResult) GetSuccess() *pbapi.EchoResponse {
	if !p.IsSetSuccess() {
		return EchoMethodResult_Success_DEFAULT
	}
	return p.Success
}

func (p *EchoMethodResult) SetSuccess(x interface{}) {
	p.Success = x.(*pbapi.EchoResponse)
}

func (p *EchoMethodResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *EchoMethodResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) EchoMethod(ctx context.Context, Req *pbapi.EchoRequest) (r *pbapi.EchoResponse, err error) {
	var _args EchoMethodArgs
	_args.Req = Req
	var _result EchoMethodResult
	if err = p.c.Call(ctx, "EchoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
